AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance using existing Security Group, EIP, and User Data

Parameters:

  InstanceName:
    Type: String
    Description: Name of the EC2 instance

  InstanceType:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /Instance/Type/Parameter
    Description: "Get the EC2 instance type from SSM Parameter Store"
  

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: Latest Amazon Linux 2 AMI ID from SSM

  

Resources:

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyName
      SubnetId: !ImportValue JimCrossStack-SubnetID
      SecurityGroupIds:
        - !ImportValue JimCrossStack-SecurityGroupID
      Tags:
        - Key: Name
          Value: !Ref InstanceName
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl enable httpd
          systemctl start httpd
          echo "<h1>Deployed with CloudFormation by Jim Nulambeh</h1>" > /var/www/html/index.html

  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EC2Instance
      EIP: !Ref ElasticIP

Outputs:

  InstanceId:
    Description: ID of the created EC2 instance
    Value: !Ref EC2Instance
    Export:
      Name: !Sub '${AWS::StackName}-EC2Instance'
 
  PublicIP:
    Description: Elastic Public IP address
    Value: !Ref ElasticIP
    Export:
      Name: !Sub '${AWS::StackName}-ElasticIP'
 
